require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Admin::BgImagesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Admin::BgImage. As you add validations to Admin::BgImage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::BgImagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all admin_bg_images as @admin_bg_images" do
      bg_image = Admin::BgImage.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:admin_bg_images)).to eq([bg_image])
    end
  end

  describe "GET #show" do
    it "assigns the requested admin_bg_image as @admin_bg_image" do
      bg_image = Admin::BgImage.create! valid_attributes
      get :show, {:id => bg_image.to_param}, valid_session
      expect(assigns(:admin_bg_image)).to eq(bg_image)
    end
  end

  describe "GET #new" do
    it "assigns a new admin_bg_image as @admin_bg_image" do
      get :new, {}, valid_session
      expect(assigns(:admin_bg_image)).to be_a_new(Admin::BgImage)
    end
  end

  describe "GET #edit" do
    it "assigns the requested admin_bg_image as @admin_bg_image" do
      bg_image = Admin::BgImage.create! valid_attributes
      get :edit, {:id => bg_image.to_param}, valid_session
      expect(assigns(:admin_bg_image)).to eq(bg_image)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Admin::BgImage" do
        expect {
          post :create, {:admin_bg_image => valid_attributes}, valid_session
        }.to change(Admin::BgImage, :count).by(1)
      end

      it "assigns a newly created admin_bg_image as @admin_bg_image" do
        post :create, {:admin_bg_image => valid_attributes}, valid_session
        expect(assigns(:admin_bg_image)).to be_a(Admin::BgImage)
        expect(assigns(:admin_bg_image)).to be_persisted
      end

      it "redirects to the created admin_bg_image" do
        post :create, {:admin_bg_image => valid_attributes}, valid_session
        expect(response).to redirect_to(Admin::BgImage.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved admin_bg_image as @admin_bg_image" do
        post :create, {:admin_bg_image => invalid_attributes}, valid_session
        expect(assigns(:admin_bg_image)).to be_a_new(Admin::BgImage)
      end

      it "re-renders the 'new' template" do
        post :create, {:admin_bg_image => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested admin_bg_image" do
        bg_image = Admin::BgImage.create! valid_attributes
        put :update, {:id => bg_image.to_param, :admin_bg_image => new_attributes}, valid_session
        bg_image.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested admin_bg_image as @admin_bg_image" do
        bg_image = Admin::BgImage.create! valid_attributes
        put :update, {:id => bg_image.to_param, :admin_bg_image => valid_attributes}, valid_session
        expect(assigns(:admin_bg_image)).to eq(bg_image)
      end

      it "redirects to the admin_bg_image" do
        bg_image = Admin::BgImage.create! valid_attributes
        put :update, {:id => bg_image.to_param, :admin_bg_image => valid_attributes}, valid_session
        expect(response).to redirect_to(bg_image)
      end
    end

    context "with invalid params" do
      it "assigns the admin_bg_image as @admin_bg_image" do
        bg_image = Admin::BgImage.create! valid_attributes
        put :update, {:id => bg_image.to_param, :admin_bg_image => invalid_attributes}, valid_session
        expect(assigns(:admin_bg_image)).to eq(bg_image)
      end

      it "re-renders the 'edit' template" do
        bg_image = Admin::BgImage.create! valid_attributes
        put :update, {:id => bg_image.to_param, :admin_bg_image => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested admin_bg_image" do
      bg_image = Admin::BgImage.create! valid_attributes
      expect {
        delete :destroy, {:id => bg_image.to_param}, valid_session
      }.to change(Admin::BgImage, :count).by(-1)
    end

    it "redirects to the admin_bg_images list" do
      bg_image = Admin::BgImage.create! valid_attributes
      delete :destroy, {:id => bg_image.to_param}, valid_session
      expect(response).to redirect_to(admin_bg_images_url)
    end
  end

end
