require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Admin::ServicesGroupsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Admin::ServicesGroup. As you add validations to Admin::ServicesGroup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::ServicesGroupsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all admin_services_groups as @admin_services_groups" do
      services_group = Admin::ServicesGroup.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:admin_services_groups)).to eq([services_group])
    end
  end

  describe "GET #show" do
    it "assigns the requested admin_services_group as @admin_services_group" do
      services_group = Admin::ServicesGroup.create! valid_attributes
      get :show, {:id => services_group.to_param}, valid_session
      expect(assigns(:admin_services_group)).to eq(services_group)
    end
  end

  describe "GET #new" do
    it "assigns a new admin_services_group as @admin_services_group" do
      get :new, {}, valid_session
      expect(assigns(:admin_services_group)).to be_a_new(Admin::ServicesGroup)
    end
  end

  describe "GET #edit" do
    it "assigns the requested admin_services_group as @admin_services_group" do
      services_group = Admin::ServicesGroup.create! valid_attributes
      get :edit, {:id => services_group.to_param}, valid_session
      expect(assigns(:admin_services_group)).to eq(services_group)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Admin::ServicesGroup" do
        expect {
          post :create, {:admin_services_group => valid_attributes}, valid_session
        }.to change(Admin::ServicesGroup, :count).by(1)
      end

      it "assigns a newly created admin_services_group as @admin_services_group" do
        post :create, {:admin_services_group => valid_attributes}, valid_session
        expect(assigns(:admin_services_group)).to be_a(Admin::ServicesGroup)
        expect(assigns(:admin_services_group)).to be_persisted
      end

      it "redirects to the created admin_services_group" do
        post :create, {:admin_services_group => valid_attributes}, valid_session
        expect(response).to redirect_to(Admin::ServicesGroup.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved admin_services_group as @admin_services_group" do
        post :create, {:admin_services_group => invalid_attributes}, valid_session
        expect(assigns(:admin_services_group)).to be_a_new(Admin::ServicesGroup)
      end

      it "re-renders the 'new' template" do
        post :create, {:admin_services_group => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested admin_services_group" do
        services_group = Admin::ServicesGroup.create! valid_attributes
        put :update, {:id => services_group.to_param, :admin_services_group => new_attributes}, valid_session
        services_group.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested admin_services_group as @admin_services_group" do
        services_group = Admin::ServicesGroup.create! valid_attributes
        put :update, {:id => services_group.to_param, :admin_services_group => valid_attributes}, valid_session
        expect(assigns(:admin_services_group)).to eq(services_group)
      end

      it "redirects to the admin_services_group" do
        services_group = Admin::ServicesGroup.create! valid_attributes
        put :update, {:id => services_group.to_param, :admin_services_group => valid_attributes}, valid_session
        expect(response).to redirect_to(services_group)
      end
    end

    context "with invalid params" do
      it "assigns the admin_services_group as @admin_services_group" do
        services_group = Admin::ServicesGroup.create! valid_attributes
        put :update, {:id => services_group.to_param, :admin_services_group => invalid_attributes}, valid_session
        expect(assigns(:admin_services_group)).to eq(services_group)
      end

      it "re-renders the 'edit' template" do
        services_group = Admin::ServicesGroup.create! valid_attributes
        put :update, {:id => services_group.to_param, :admin_services_group => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested admin_services_group" do
      services_group = Admin::ServicesGroup.create! valid_attributes
      expect {
        delete :destroy, {:id => services_group.to_param}, valid_session
      }.to change(Admin::ServicesGroup, :count).by(-1)
    end

    it "redirects to the admin_services_groups list" do
      services_group = Admin::ServicesGroup.create! valid_attributes
      delete :destroy, {:id => services_group.to_param}, valid_session
      expect(response).to redirect_to(admin_services_groups_url)
    end
  end

end
