default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: alexey
  password: password

development:
  <<: *default
  database: HarmonyShop_development

test:
  <<: *default
  database: HarmonyShop_test

production:
  <<: *default
  database: HarmonyShop_production
  username: <%= ENV['APP_DATABASE_USER'] %>
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
